services:
  api:
    build: ./api
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  bot:
    build: ./bot
    env_file: .env
    depends_on:
      - api
    restart: unless-stopped
