services:
  api:
    build: ./api
    env_file: ./.env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SERVER_URL=${SERVER_URL}
      - SERVER_TOKEN=${SERVER_TOKEN}
      - BOT_SHARED_SECRET=${BOT_SHARED_SECRET}
    expose:
      - "8000"
    ports:
      - "${API_PORT:-8000}:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://localhost:8000/healthz >/dev/null 2>&1 || exit 1",
        ]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  bot:
    build: ./bot
    env_file: ./.env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - FASTAPI_URL=http://api:8000
      - BOT_SHARED_SECRET=${BOT_SHARED_SECRET}
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: fastapi_discord_net
