services:
  bot:
    build: ./bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GUILD_ID=${GUILD_ID}
      - SERVER_ID=${SERVER_ID}
      - SERVER_TOKEN=${SERVER_TOKEN}
      - SERVER_URL=${SERVER_URL}
      - RCON_HOST=${RCON_HOST}
      - RCON_PORT=${RCON_PORT}
      - RCON_PASSWORD=${RCON_PASSWORD}
    volumes:
      - ./bot/logs:/app/logs
    restart: unless-stopped
